language: Java
sudo: required
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
- ./gradlew sonarqube
deploy:
  provider: heroku
  api_key:
    secure: cv1veWcY6cpdvKLFnbqVBbe4WH2oAUoGOKzLojyypKxHoAMZM65kybJG6JQJnmOUk0izjpQ+S1XF8WORBSMWOHX6zfiwCYtt1U+OzFqq5OeGNGmOkxhZzqT2P5LOWWVS7icN6SFx11u2e8tI/t5ljj72WJSWCaHwwLkCh8TNnU5Fil7Y+QaMLNPeMgZExB2qaY6kzrJHYVTYZ7SaPbiWoyOV/lmqSFTlXK325PeP+qT1/o4eBe52q7EcjYJBTa7jwcqVpfWHyUhcoxOB6dXeT4xvozd0nDRvTXcvENi0r6O+iCd96acLEaco8fBYOND8kmxIKcO7cN/LMWh5xaw2zUf36NFNRdOCTBVNh0losLdstBKfZH+jd6iwUO8GsT/Qfuo6f3DQaleqrlhWOEoP8/Z8w2Jydw4Go1Ht0JzNWaD9MZ2fMKScOhrg9KPqxR1PH9WA2N7yuhOn4UlcMKszxZdSPeqRHDbcxtTmwhSQPLyPgYKpF8sEqC4PgFOA8DpvdyvBvK9vzM6drTEkKzLwZhIrd+byQauV03+mmRRSniUNdrqWXFT7RKwx60yR4Lgtw0nCqLaX7Ktww1Spnn//5uM5EkbwFHacS9PzRIXJx5ZjiWolVM0YKPOfZRqjql0tfMlSHORWg+sqNp26+Jzxugm+BR0K6il15eUxeO8MPxs=
  app: allocation-receiver-staging
  skip_cleanup: true
  on:
    repo: spolnik/trading-office-allocation-message-receiver
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
services:
- rabbitmq